### ISSUE TITLE
Write then read of VDP vram should return previously written value

### ISSUE THREAD

**Issue by nrivard** [visrealm/vrEmuTms9918#4]
According to this [hardware deep-dive](http://bifi.msxnet.org/msxnet/tech/tms9918a.txt) VDP hardware uses a read-ahead buffer for speed and other reasons. This results in some interesting behavior if you mix reads and writes. Most obviously:
1. write a value to the data port (mode=0)
2. read from the data port (mode=0)

Due to the read-ahead buffer, you will get back the written value, you will _not_ get the value advanced by the pointer. There are other behavioral oddities here as well regarding how read and write deals with the vram pointer.

When reading:
1. value in read-ahead buffer is returned
2. read-ahead buffer is updated with value pointed at by _current_ vram address
3. vram address is incremented

When writing:
1. vram pointed at by vram address is updated with new value
2. read-ahead buffer is set to new value as well
3. vram address is incremented

I have verified this with my own hardware but worth checking on yours as well. I'm using TMS9128.

**Comment by nrivard** [comment]
Oh! another oddity: the initial vram pointer is setup differently depending on whether the vram write mask (`0x40`) is set or not. if write is set, then behavior as written is correct: vram pointer is just set to the passed in values. but if read is set (or write is not set i guess is a better way to put it), then it follows above read conventions: read-ahead buffer is primed with value pointed at by the passed-in values, and the pointer is incremented.

So, if you set vram address as a "read", then immediately _write_ a value, it will be at the passed in values + 1. ex:
1. write `0x00` to register port (mode=1)
2. write `0x10` to register port (mode=1)
3. write` 0xAA` to data port (mode=0)

then `0xAA` will be at `0x1001`, not `0x1000`.

**Comment by visrealm** [comment]
Thanks for this. I'll take a look.

**Comment by nrivard** [comment]
I have written a solution to this and my other ticket starting around [here](https://github.com/nrivard/vrEmuTms9918/blob/main/Sources/VideoDisplayProcessor/VideoDisplayProcessor.c#L106). I also wrote tests to verify this behavior [here](https://github.com/nrivard/vrEmuTms9918/blob/main/Tests/VideoDisplayProcessorTests/VDPTests.swift#L116) if you can utilize them (they're in swift bc my ultimate aim here is to have a C-based swift package but the actual usecases can be ported). Like I said, I have verified most of these with the actual hardware but you are encouraged to double-check that work on your own hardware.

**Comment by nrivard** [comment]
Also, thanks for writing this! 😄

**Comment by visrealm** [comment]
Closing as fixed with commit ae1e404
